spring.application.name=resume-ai-telegram-bot
telegram.bot.token=8807085815:AAFBIdPZU4D8lF_yJghala5P7YPja-EiwfM

spring.ai.google.genai.api-key=AIzaSyA6rJcm4CzIspOV6ykk8y2e1It31qdcCq8
spring.ai.google.genai.chat.model=gemini-3.5-flash
spring.ai.google.genai.chat.response-mime-type=application/json