spring.application.name=resume-ai-telegram-bot
telegram.bot.token={TELEGRAM_BOT_TOKEN}

spring.ai.google.genai.api-key={AI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash
spring.ai.google.genai.chat.response-mime-type=application/json